# Generated by Django 3.1.7 on 2021-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punnyWebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pun',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
