# Generated by Django 3.1.7 on 2021-08-15 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('punnyWebapp', '0002_auto_20210811_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pun',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
